# Generated by Django 5.2.7 on 2025-10-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryShopApp', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default='250g,500g,1kg', max_length=255),
        ),
    ]
