# Generated by Django 5.2.7 on 2025-10-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryShopApp', '0007_remove_product_updated_at_product_quantity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_options',
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
