# Generated by Django 6.0.6 on 2026-06-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryShopApp', '0010_order_delivery_boy_userprofile_is_delivery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Online Payment (Razorpay)'), ('cod', 'Cash on Delivery (COD)')], default='razorpay', max_length=20),
        ),
    ]
